//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGSDATool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MGSDATool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1F01=Ä
        ///1F02=Å
        ///1F03=Ç
        ///1F04=É
        ///1F05=Ñ
        ///1F06=Ö
        ///1F07=Ü
        ///1F08=á
        ///1F09=à
        ///1F0A=â
        ///1F0B=ä
        ///1F0C=ã
        ///1F0D=å
        ///1F0E=ç
        ///1F0F=é
        ///1F10=è
        ///1F11=ê
        ///1F12=ë
        ///1F13=í
        ///1F14=ì
        ///1F15=î
        ///1F16=ï
        ///1F17=ñ
        ///1F18=ó
        ///1F19=ò
        ///1F1A=ô
        ///1F1B=ö
        ///1F1C=õ
        ///1F1D=ú
        ///1F1E=ù
        ///1F1F=û
        ///1F20=ü
        ///1F21=†
        ///1F22=°
        ///1F23=¢
        ///1F24=£
        ///1F25=§
        ///1F26=•
        ///1F27=¶
        ///1F28=ß
        ///1F29=®
        ///1F2A=©
        ///1F2B=™
        ///1F2C=´
        ///1F2D=¨
        ///1F2E=≠
        ///1F2F=Æ
        ///1F30=Ø
        ///1F31=∞
        ///1F32=±
        ///1F33=≤
        ///1F34=≥
        ///1F35=¥
        ///1F36=µ
        ///1F37=∂
        ///1F38=∑
        ///1F39=∏
        ///1F3A=π
        ///1F3B=∫
        ///1F3C=ª
        ///1F3D=º
        ///1F3E=Ω
        ///1F3F=æ
        ///1F40=ø
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterTable {
            get {
                return ResourceManager.GetString("CharacterTable", resourceCulture);
            }
        }
    }
}
